apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: dldata-app

build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
  artifacts:
    - image: api
      context: api
      docker:
        dockerfile: docker/Dockerfile
      sync:
        infer:
          - "*.py"
          - "**/*.py"
    - image: alembic
      context: database
      docker:
        dockerfile: docker/Dockerfile
      sync:
        infer:
          - "alembic/**/*"
          - "alembic.ini"

deploy:
  helm:
    releases:
      - name: dldata-app
        namespace: default
        chartPath: dldata-app
        valuesFiles:
          - dldata-app/values.yaml
        setValueTemplates:
          api.image.repository: "{{.IMAGE_REPO_api}}"
          api.image.tag: "{{.IMAGE_TAG_api}}@{{.IMAGE_DIGEST_api}}"
          api.replicas: 1
          postgres.replicas: 1
          alembic.image.repository: "{{.IMAGE_REPO_alembic}}"
          alembic.image.tag: "{{.IMAGE_TAG_alembic}}@{{.IMAGE_DIGEST_alembic}}"
          host: dldata.ilya.kapernikov.com

portForward:
  - resourceType: service
    resourceName: api
    port: 8000
    localPort: 8000
    namespace: default
