apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: dldata-app

deploy:
  helm:
    releases:
      - name: dldata-app
        chartPath: dldata-app
        setValueTemplates:
          postgres.replicas: 1
          postgres.password: DLDataPass123
