apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migration
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      imagePullSecrets:
        - name: registry-creds
      containers:
      - name: alembic-migration
        image: "{{ .Values.alembic.image }}"
        command: ["alembic", "upgrade", "head"]
        env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: dldata-app-postgres-pguser-dldata-app-postgres
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dldata-app-postgres-pguser-dldata-app-postgres
                  key: password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: dldata-app-postgres-pguser-dldata-app-postgres
                  key: dbname
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: dldata-app-postgres-pguser-dldata-app-postgres
                  key: host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: dldata-app-postgres-pguser-dldata-app-postgres
                  key: port
      restartPolicy: OnFailure