apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dldata-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000