version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      DB_NAME: dldata
      DB_USER: dldata
      DB_PWD: dldatapass
      DB_HOST: db
      DEBUGMODE: "true"

  db:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dldata
      POSTGRES_DB: dldata
      POSTGRES_PASSWORD: dldatapass

volumes:
  postgres-data:
